export const quotesData = [
  { id: 1, title: 'Inspiration', quote: 'The only way to do great work is to love what you do.' },
  { id: 2, title: 'Success', quote: 'Success is not final, failure is not fatal: It is the courage to continue that counts.' },
  { id: 3, title: 'Wisdom', quote: 'The only true wisdom is in knowing you know nothing.' },
  { id: 4, title: 'Courage', quote: 'Courage is not the absence of fear, but the triumph over it.' },
  { id: 5, title: 'Dream', quote: 'The future belongs to those who believe in the beauty of their dreams.' },
  { id: 6, title: 'Change', quote: 'Be the change that you wish to see in the world.' },
  { id: 7, title: 'Knowledge', quote: 'The only source of knowledge is experience.' },
  { id: 8, title: 'Hope', quote: 'Hope is being able to see that there is light despite all of the darkness.' },
  { id: 9, title: 'Strength', quote: 'That which does not kill us makes us stronger.' },
  { id: 10, title: 'Time', quote: 'The two most powerful warriors are patience and time.' },
  { id: 11, title: 'Creativity', quote: 'Creativity is intelligence having fun.' },
  { id: 12, title: 'Leadership', quote: 'A leader is one who knows the way, goes the way, and shows the way.' },
  { id: 13, title: 'Happiness', quote: 'Happiness is not something ready made. It comes from your own actions.' },
  { id: 14, title: 'Growth', quote: 'The only limit to our realization of tomorrow is our doubts of today.' },
  { id: 15, title: 'Perseverance', quote: 'It does not matter how slowly you go as long as you do not stop.' },
  { id: 16, title: 'Friendship', quote: 'A real friend is one who walks in when the rest of the world walks out.' },
  { id: 17, title: 'Innovation', quote: 'Innovation distinguishes between a leader and a follower.' },
  { id: 18, title: 'Gratitude', quote: 'Gratitude makes sense of our past, brings peace for today, and creates a vision for tomorrow.' },
  { id: 19, title: 'Excellence', quote: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.' },
  { id: 20, title: 'Simplicity', quote: 'Simplicity is the ultimate sophistication.' },
  { id: 21, title: 'Determination', quote: 'The difference between the impossible and the possible lies in a person\'s determination.' },
  { id: 22, title: 'Optimism', quote: 'Keep your face always toward the sunshine—and shadows will fall behind you.' },
  { id: 23, title: 'Integrity', quote: 'Real integrity is doing the right thing, knowing that nobody\'s going to know whether you did it or not.' },
  { id: 24, title: 'Adventure', quote: 'Life is either a daring adventure or nothing at all.' },
  { id: 25, title: 'Resilience', quote: 'Our greatest glory is not in never falling, but in rising every time we fall.' },
  { id: 26, title: 'Compassion', quote: 'A kind word can change someone\'s entire day.' },
  { id: 27, title: 'Ambition', quote: 'Ambition is the path to success. Persistence is the vehicle you arrive in.' },
  { id: 28, title: 'Balance', quote: 'Happiness is not a matter of intensity but of balance, order, rhythm and harmony.' },
  { id: 29, title: 'Curiosity', quote: 'The important thing is not to stop questioning. Curiosity has its own reason for existing.' },
  { id: 30, title: 'Empathy', quote: 'When you show deep empathy toward others, their defensive energy goes down, and positive energy replaces it.' },
  { id: 31, title: 'Freedom', quote: 'For to be free is not merely to cast off one\'s chains, but to live in a way that respects and enhances the freedom of others.' },
  { id: 32, title: 'Generosity', quote: 'No one has ever become poor by giving.' },
  { id: 33, title: 'Humility', quote: 'True humility is not thinking less of yourself; it is thinking of yourself less.' },
  { id: 34, title: 'Imagination', quote: 'Imagination is more important than knowledge.' },
  { id: 35, title: 'Joy', quote: 'Find ecstasy in life; the mere sense of living is joy enough.' },
  { id: 36, title: 'Kindness', quote: 'No act of kindness, no matter how small, is ever wasted.' },
  { id: 37, title: 'Learning', quote: 'Live as if you were to die tomorrow. Learn as if you were to live forever.' },
  { id: 38, title: 'Mindfulness', quote: 'The present moment is the only time over which we have dominion.' },
  { id: 39, title: 'Opportunity', quote: 'Opportunities don\'t happen. You create them.' },
  { id: 40, title: 'Passion', quote: 'Passion is energy. Feel the power that comes from focusing on what excites you.' },
  { id: 41, title: 'Quality', quote: 'Quality is not an act, it is a habit.' },
  { id: 42, title: 'Respect', quote: 'Respect for ourselves guides our morals; respect for others guides our manners.' },
  { id: 43, title: 'Service', quote: 'The best way to find yourself is to lose yourself in the service of others.' },
  { id: 44, title: 'Teamwork', quote: 'Alone we can do so little; together we can do so much.' },
  { id: 45, title: 'Understanding', quote: 'The only way to understand is to love.' },
  { id: 46, title: 'Vision', quote: 'The only thing worse than being blind is having sight but no vision.' },
  { id: 47, title: 'Wisdom', quote: 'The only true wisdom is in knowing you know nothing.' },
  { id: 48, title: 'eXcellence', quote: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.' },
  { id: 49, title: 'Youth', quote: 'Youth is the gift of nature, but age is a work of art.' },
  { id: 50, title: 'Zeal', quote: 'Zeal will do more than knowledge.' },
  { id: 51, title: 'Achievement', quote: 'What you get by achieving your goals is not as important as what you become by achieving your goals.' },
  { id: 52, title: 'Belief', quote: 'Believe you can and you\'re halfway there.' },
  { id: 53, title: 'Confidence', quote: 'With confidence, you have won before you have started.' },
  { id: 54, title: 'Discipline', quote: 'Discipline is the bridge between goals and accomplishment.' },
  { id: 55, title: 'Effort', quote: 'The only place where success comes before work is in the dictionary.' },
  { id: 56, title: 'Focus', quote: 'The successful warrior is the average man, with laser-like focus.' },
  { id: 57, title: 'Gratitude', quote: 'Gratitude turns what we have into enough.' },
  { id: 58, title: 'Humility', quote: 'Pride makes us artificial and humility makes us real.' },
  { id: 59, title: 'Intuition', quote: 'The only real valuable thing is intuition.' },
  { id: 60, title: 'Journey', quote: 'The journey of a thousand miles begins with one step.' },
  { id: 61, title: 'Knowledge', quote: 'Knowledge is power.' },
  { id: 62, title: 'Love', quote: 'Where there is love there is life.' },
  { id: 63, title: 'Motivation', quote: 'People often say that motivation doesn\'t last. Well, neither does bathing - that\'s why we recommend it daily.' },
  { id: 64, title: 'Nature', quote: 'Look deep into nature, and then you will understand everything better.' },
  { id: 65, title: 'Originality', quote: 'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.' },
  { id: 66, title: 'Patience', quote: 'Patience is not the ability to wait, but the ability to keep a good attitude while waiting.' },
  { id: 67, title: 'Quality', quote: 'Quality is never an accident; it is always the result of intelligent effort.' },
  { id: 68, title: 'Resilience', quote: 'It\'s not whether you get knocked down, it\'s whether you get up.' },
  { id: 69, title: 'Success', quote: 'Success is walking from failure to failure with no loss of enthusiasm.' },
  { id: 70, title: 'Trust', quote: 'The best way to find out if you can trust somebody is to trust them.' },
  { id: 71, title: 'Understanding', quote: 'Seek first to understand, then to be understood.' },
  { id: 72, title: 'Victory', quote: 'Victory is sweetest when you\'ve known defeat.' },
  { id: 73, title: 'Wisdom', quote: 'Knowing yourself is the beginning of all wisdom.' },
  { id: 74, title: 'eXcellence', quote: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.' },
  { id: 75, title: 'Youth', quote: 'The young do not know enough to be prudent, and therefore they attempt the impossible - and achieve it, generation after generation.' },
  { id: 76, title: 'Zeal', quote: 'Zeal without knowledge is fire without light.' },
  { id: 77, title: 'Ambition', quote: 'Ambition is the path to success. Persistence is the vehicle you arrive in.' },
  { id: 78, title: 'Bravery', quote: 'Bravery is being the only one who knows you\'re afraid.' },
  { id: 79, title: 'Creativity', quote: 'Creativity is just connecting things.' },
  { id: 80, title: 'Determination', quote: 'Determination is the wake-up call to the human will.' },
  { id: 81, title: 'Excellence', quote: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.' },
  { id: 82, title: 'Faith', quote: 'Faith is taking the first step even when you don\'t see the whole staircase.' },
  { id: 83, title: 'Genius', quote: 'Genius is one percent inspiration and ninety-nine percent perspiration.' },
  { id: 84, title: 'Honesty', quote: 'Honesty is the first chapter in the book of wisdom.' },
  { id: 85, title: 'Imagination', quote: 'Logic will get you from A to B. Imagination will take you everywhere.' },
  { id: 86, title: 'Joy', quote: 'The joy of life comes from our encounters with new experiences.' },
  { id: 87, title: 'Knowledge', quote: 'The only true wisdom is in knowing you know nothing.' },
  { id: 88, title: 'Leadership', quote: 'A leader is best when people barely know he exists, when his work is done, his aim fulfilled, they will say: we did it ourselves.' },
  { id: 89, title: 'Motivation', quote: 'What you get by achieving your goals is not as important as what you become by achieving your goals.' },
  { id: 90, title: 'Nature', quote: 'In all things of nature there is something of the marvelous.' },
  { id: 91, title: 'Opportunity', quote: 'In the middle of difficulty lies opportunity.' },
  { id: 92, title: 'Perseverance', quote: 'Perseverance is not a long race; it is many short races one after the other.' },
  { id: 93, title: 'Quality', quote: 'Quality means doing it right when no one is looking.' },
  { id: 94, title: 'Respect', quote: 'I speak to everyone in the same way, whether he is the garbage man or the president of the university.' },
  { id: 95, title: 'Success', quote: 'Success is not the key to happiness. Happiness is the key to success.' },
  { id: 96, title: 'Teamwork', quote: 'Coming together is a beginning, staying together is progress, and working together is success.' },
  { id: 97, title: 'Unity', quote: 'Unity is strength... when there is teamwork and collaboration, wonderful things can be achieved.' },
  { id: 98, title: 'Vision', quote: 'The only thing worse than being blind is having sight but no vision.' },
  { id: 99, title: 'Wisdom', quote: 'The only true wisdom is in knowing you know nothing.' },
  { id: 100, title: 'eXcellence', quote: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.' }
];